services:
  # Core Service (gRPC + REST)
  coreservice:
    build:
      context: .
      dockerfile: SERVICES/Core.Service/Core.Service/Dockerfile
    container_name: zapfinance-coreservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - USE_IN_MEMORY_DATA=true
    ports:
      - "5001:80"
    networks:
      - zapfinance-network
    restart: unless-stopped

  # Mobile Aggregator Gateway
  mobileaggregator:
    build:
      context: .
      dockerfile: GATEWAYS/MobileAggregator/MobileAggregator/Dockerfile
    container_name: zapfinance-mobileaggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__CoreService=http://coreservice:80
      - Jwt__Key=ZapFinance-Super-Secret-Key-For-JWT-Token-Generation-2024
      - Jwt__Issuer=ZapFinance.MobileAggregator
      - Jwt__Audience=ZapFinance.Mobile
    ports:
      - "5002:80"
    depends_on:
      coreservice:
        condition: service_started
    networks:
      - zapfinance-network
    restart: unless-stopped

  # Web Gateway (placeholder for future implementation)
  webgateway:
    build:
      context: .
      dockerfile: GATEWAYS/MobileAggregator/MobileAggregator/Dockerfile  # Usando MobileAggregator como base por enquanto
    container_name: zapfinance-webgateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__CoreService=http://coreservice:80
      - Jwt__Key=ZapFinance-Super-Secret-Key-For-JWT-Token-Generation-2024
      - Jwt__Issuer=ZapFinance.WebGateway
      - Jwt__Audience=ZapFinance.Web
    ports:
      - "5003:80"
    depends_on:
      - coreservice
    networks:
      - zapfinance-network
    restart: unless-stopped

  # Integration Gateway (placeholder for future implementation)
  integrationgateway:
    build:
      context: .
      dockerfile: GATEWAYS/MobileAggregator/MobileAggregator/Dockerfile  # Usando MobileAggregator como base por enquanto
    container_name: zapfinance-integrationgateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__CoreService=http://coreservice:80
      - Jwt__Key=ZapFinance-Super-Secret-Key-For-JWT-Token-Generation-2024
      - Jwt__Issuer=ZapFinance.IntegrationGateway
      - Jwt__Audience=ZapFinance.Integration
    ports:
      - "5004:80"
    depends_on:
      - coreservice
    networks:
      - zapfinance-network
    restart: unless-stopped

  # Nginx Load Balancer / API Gateway (disabled due to volume sharing issues)
  # nginx:
  #   image: nginx:alpine
  #   container_name: zapfinance-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - mobileaggregator
  #     - webgateway
  #     - integrationgateway
  #   networks:
  #     - zapfinance-network
  #   restart: unless-stopped

# volumes:
#   sqlserver_data:
#     driver: local

networks:
  zapfinance-network:
    driver: bridge
